apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: vuvuongvi/knote-js:1.0.0
          ports: 
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          #cai nay la bat buoc download ve docker image, ngay ca khi no da co trong may 
          imagePullPolicy: Always